// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.show.grpc;

public interface PersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
