// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.show.grpc;

/**
 * Protobuf type {@code proto.PersonResponseList}
 */
public  final class PersonResponseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.PersonResponseList)
    PersonResponseListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersonResponseList.newBuilder() to construct.
  private PersonResponseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersonResponseList() {
    personResonse_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PersonResponseList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              personResonse_ = new java.util.ArrayList<com.show.grpc.PersonResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            personResonse_.add(
                input.readMessage(com.show.grpc.PersonResponse.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        personResonse_ = java.util.Collections.unmodifiableList(personResonse_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.show.grpc.Person.internal_static_proto_PersonResponseList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.show.grpc.Person.internal_static_proto_PersonResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.show.grpc.PersonResponseList.class, com.show.grpc.PersonResponseList.Builder.class);
  }

  public static final int PERSONRESONSE_FIELD_NUMBER = 1;
  private java.util.List<com.show.grpc.PersonResponse> personResonse_;
  /**
   * <code>repeated .proto.PersonResponse personResonse = 1;</code>
   */
  public java.util.List<com.show.grpc.PersonResponse> getPersonResonseList() {
    return personResonse_;
  }
  /**
   * <code>repeated .proto.PersonResponse personResonse = 1;</code>
   */
  public java.util.List<? extends com.show.grpc.PersonResponseOrBuilder> 
      getPersonResonseOrBuilderList() {
    return personResonse_;
  }
  /**
   * <code>repeated .proto.PersonResponse personResonse = 1;</code>
   */
  public int getPersonResonseCount() {
    return personResonse_.size();
  }
  /**
   * <code>repeated .proto.PersonResponse personResonse = 1;</code>
   */
  public com.show.grpc.PersonResponse getPersonResonse(int index) {
    return personResonse_.get(index);
  }
  /**
   * <code>repeated .proto.PersonResponse personResonse = 1;</code>
   */
  public com.show.grpc.PersonResponseOrBuilder getPersonResonseOrBuilder(
      int index) {
    return personResonse_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < personResonse_.size(); i++) {
      output.writeMessage(1, personResonse_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < personResonse_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, personResonse_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.show.grpc.PersonResponseList)) {
      return super.equals(obj);
    }
    com.show.grpc.PersonResponseList other = (com.show.grpc.PersonResponseList) obj;

    if (!getPersonResonseList()
        .equals(other.getPersonResonseList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPersonResonseCount() > 0) {
      hash = (37 * hash) + PERSONRESONSE_FIELD_NUMBER;
      hash = (53 * hash) + getPersonResonseList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.show.grpc.PersonResponseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.show.grpc.PersonResponseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.show.grpc.PersonResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.show.grpc.PersonResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.show.grpc.PersonResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.show.grpc.PersonResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.show.grpc.PersonResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.show.grpc.PersonResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.show.grpc.PersonResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.show.grpc.PersonResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.show.grpc.PersonResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.show.grpc.PersonResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.show.grpc.PersonResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.PersonResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.PersonResponseList)
      com.show.grpc.PersonResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.show.grpc.Person.internal_static_proto_PersonResponseList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.show.grpc.Person.internal_static_proto_PersonResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.show.grpc.PersonResponseList.class, com.show.grpc.PersonResponseList.Builder.class);
    }

    // Construct using com.show.grpc.PersonResponseList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPersonResonseFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (personResonseBuilder_ == null) {
        personResonse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        personResonseBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.show.grpc.Person.internal_static_proto_PersonResponseList_descriptor;
    }

    @java.lang.Override
    public com.show.grpc.PersonResponseList getDefaultInstanceForType() {
      return com.show.grpc.PersonResponseList.getDefaultInstance();
    }

    @java.lang.Override
    public com.show.grpc.PersonResponseList build() {
      com.show.grpc.PersonResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.show.grpc.PersonResponseList buildPartial() {
      com.show.grpc.PersonResponseList result = new com.show.grpc.PersonResponseList(this);
      int from_bitField0_ = bitField0_;
      if (personResonseBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          personResonse_ = java.util.Collections.unmodifiableList(personResonse_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.personResonse_ = personResonse_;
      } else {
        result.personResonse_ = personResonseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.show.grpc.PersonResponseList) {
        return mergeFrom((com.show.grpc.PersonResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.show.grpc.PersonResponseList other) {
      if (other == com.show.grpc.PersonResponseList.getDefaultInstance()) return this;
      if (personResonseBuilder_ == null) {
        if (!other.personResonse_.isEmpty()) {
          if (personResonse_.isEmpty()) {
            personResonse_ = other.personResonse_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePersonResonseIsMutable();
            personResonse_.addAll(other.personResonse_);
          }
          onChanged();
        }
      } else {
        if (!other.personResonse_.isEmpty()) {
          if (personResonseBuilder_.isEmpty()) {
            personResonseBuilder_.dispose();
            personResonseBuilder_ = null;
            personResonse_ = other.personResonse_;
            bitField0_ = (bitField0_ & ~0x00000001);
            personResonseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPersonResonseFieldBuilder() : null;
          } else {
            personResonseBuilder_.addAllMessages(other.personResonse_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.show.grpc.PersonResponseList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.show.grpc.PersonResponseList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.show.grpc.PersonResponse> personResonse_ =
      java.util.Collections.emptyList();
    private void ensurePersonResonseIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        personResonse_ = new java.util.ArrayList<com.show.grpc.PersonResponse>(personResonse_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.show.grpc.PersonResponse, com.show.grpc.PersonResponse.Builder, com.show.grpc.PersonResponseOrBuilder> personResonseBuilder_;

    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public java.util.List<com.show.grpc.PersonResponse> getPersonResonseList() {
      if (personResonseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(personResonse_);
      } else {
        return personResonseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public int getPersonResonseCount() {
      if (personResonseBuilder_ == null) {
        return personResonse_.size();
      } else {
        return personResonseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public com.show.grpc.PersonResponse getPersonResonse(int index) {
      if (personResonseBuilder_ == null) {
        return personResonse_.get(index);
      } else {
        return personResonseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public Builder setPersonResonse(
        int index, com.show.grpc.PersonResponse value) {
      if (personResonseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonResonseIsMutable();
        personResonse_.set(index, value);
        onChanged();
      } else {
        personResonseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public Builder setPersonResonse(
        int index, com.show.grpc.PersonResponse.Builder builderForValue) {
      if (personResonseBuilder_ == null) {
        ensurePersonResonseIsMutable();
        personResonse_.set(index, builderForValue.build());
        onChanged();
      } else {
        personResonseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public Builder addPersonResonse(com.show.grpc.PersonResponse value) {
      if (personResonseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonResonseIsMutable();
        personResonse_.add(value);
        onChanged();
      } else {
        personResonseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public Builder addPersonResonse(
        int index, com.show.grpc.PersonResponse value) {
      if (personResonseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePersonResonseIsMutable();
        personResonse_.add(index, value);
        onChanged();
      } else {
        personResonseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public Builder addPersonResonse(
        com.show.grpc.PersonResponse.Builder builderForValue) {
      if (personResonseBuilder_ == null) {
        ensurePersonResonseIsMutable();
        personResonse_.add(builderForValue.build());
        onChanged();
      } else {
        personResonseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public Builder addPersonResonse(
        int index, com.show.grpc.PersonResponse.Builder builderForValue) {
      if (personResonseBuilder_ == null) {
        ensurePersonResonseIsMutable();
        personResonse_.add(index, builderForValue.build());
        onChanged();
      } else {
        personResonseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public Builder addAllPersonResonse(
        java.lang.Iterable<? extends com.show.grpc.PersonResponse> values) {
      if (personResonseBuilder_ == null) {
        ensurePersonResonseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, personResonse_);
        onChanged();
      } else {
        personResonseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public Builder clearPersonResonse() {
      if (personResonseBuilder_ == null) {
        personResonse_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        personResonseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public Builder removePersonResonse(int index) {
      if (personResonseBuilder_ == null) {
        ensurePersonResonseIsMutable();
        personResonse_.remove(index);
        onChanged();
      } else {
        personResonseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public com.show.grpc.PersonResponse.Builder getPersonResonseBuilder(
        int index) {
      return getPersonResonseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public com.show.grpc.PersonResponseOrBuilder getPersonResonseOrBuilder(
        int index) {
      if (personResonseBuilder_ == null) {
        return personResonse_.get(index);  } else {
        return personResonseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public java.util.List<? extends com.show.grpc.PersonResponseOrBuilder> 
         getPersonResonseOrBuilderList() {
      if (personResonseBuilder_ != null) {
        return personResonseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(personResonse_);
      }
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public com.show.grpc.PersonResponse.Builder addPersonResonseBuilder() {
      return getPersonResonseFieldBuilder().addBuilder(
          com.show.grpc.PersonResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public com.show.grpc.PersonResponse.Builder addPersonResonseBuilder(
        int index) {
      return getPersonResonseFieldBuilder().addBuilder(
          index, com.show.grpc.PersonResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.PersonResponse personResonse = 1;</code>
     */
    public java.util.List<com.show.grpc.PersonResponse.Builder> 
         getPersonResonseBuilderList() {
      return getPersonResonseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.show.grpc.PersonResponse, com.show.grpc.PersonResponse.Builder, com.show.grpc.PersonResponseOrBuilder> 
        getPersonResonseFieldBuilder() {
      if (personResonseBuilder_ == null) {
        personResonseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.show.grpc.PersonResponse, com.show.grpc.PersonResponse.Builder, com.show.grpc.PersonResponseOrBuilder>(
                personResonse_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        personResonse_ = null;
      }
      return personResonseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.PersonResponseList)
  }

  // @@protoc_insertion_point(class_scope:proto.PersonResponseList)
  private static final com.show.grpc.PersonResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.show.grpc.PersonResponseList();
  }

  public static com.show.grpc.PersonResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonResponseList>
      PARSER = new com.google.protobuf.AbstractParser<PersonResponseList>() {
    @java.lang.Override
    public PersonResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PersonResponseList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PersonResponseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonResponseList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.show.grpc.PersonResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

