// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.show.grpc;

public final class Person {
  private Person() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PersonRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PersonRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PersonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PersonResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_StreamResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_PersonResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_PersonResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\022\005proto\"\035\n\rPersonRequest\022\014" +
      "\n\004name\030\001 \001(\t\"8\n\016PersonResponse\022\014\n\004name\030\001" +
      " \001(\t\022\n\n\002id\030\002 \001(\005\022\014\n\004city\030\003 \001(\t\"%\n\rStream" +
      "Request\022\024\n\014request_info\030\001 \001(\t\"\'\n\016StreamR" +
      "esponse\022\025\n\rresponse_info\030\001 \001(\t\"B\n\022Person" +
      "ResponseList\022,\n\rpersonResonse\030\001 \003(\0132\025.pr" +
      "oto.PersonResponse2\222\002\n\rPersonService\0228\n\t" +
      "GetPerson\022\024.proto.PersonRequest\032\025.proto." +
      "PersonResponse\022@\n\017GetPersonByName\022\024.prot" +
      "o.PersonRequest\032\025.proto.PersonResponse0\001" +
      "\022J\n\025GetPersonWapperByName\022\024.proto.Person" +
      "Request\032\031.proto.PersonResponseList(\001\0229\n\006" +
      "BiTalk\022\024.proto.StreamRequest\032\025.proto.Str" +
      "eamResponse(\0010\001B\033\n\rcom.show.grpcB\006Person" +
      "H\001P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_PersonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_PersonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PersonRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_proto_PersonResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_PersonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PersonResponse_descriptor,
        new java.lang.String[] { "Name", "Id", "City", });
    internal_static_proto_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StreamRequest_descriptor,
        new java.lang.String[] { "RequestInfo", });
    internal_static_proto_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_StreamResponse_descriptor,
        new java.lang.String[] { "ResponseInfo", });
    internal_static_proto_PersonResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_PersonResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_PersonResponseList_descriptor,
        new java.lang.String[] { "PersonResonse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
