// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.show.grpc;

public interface PersonResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PersonResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.PersonResponse personResonse = 1;</code>
   */
  java.util.List<com.show.grpc.PersonResponse> 
      getPersonResonseList();
  /**
   * <code>repeated .proto.PersonResponse personResonse = 1;</code>
   */
  com.show.grpc.PersonResponse getPersonResonse(int index);
  /**
   * <code>repeated .proto.PersonResponse personResonse = 1;</code>
   */
  int getPersonResonseCount();
  /**
   * <code>repeated .proto.PersonResponse personResonse = 1;</code>
   */
  java.util.List<? extends com.show.grpc.PersonResponseOrBuilder> 
      getPersonResonseOrBuilderList();
  /**
   * <code>repeated .proto.PersonResponse personResonse = 1;</code>
   */
  com.show.grpc.PersonResponseOrBuilder getPersonResonseOrBuilder(
      int index);
}
